//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNewAspWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stud
    {
        internal int id;

        public int std_id { get; set; }
        public string std_name { get; set; }
        public string std_gender { get; set; }
        public Nullable<int> std_age { get; set; }
        public Nullable<int> std_claaas { get; set; }
        public Nullable<int> t_id { get; set; }
    }
}
